services:
  desk-power-guardian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desk-power-guardian
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:8080
    volumes:
      - ./data:/app/data
